### ISSUE TITLE
SYSTEM_STATE_NAME KeyError: 97 when in state "safety discharge" ("Sicherheitsentladung")

### ISSUE THREAD

**Issue by neubi4** [mchwalisz/pysenec#6]
Hi,

my V2.1 got an firmware update an hour ago and is now in state "safety discharge" ("Sicherheitsentladung").

The Home Assistant Integration does not work anymore, error in log is
```
  File "/usr/local/lib/python3.9/site-packages/pysenec/__init__.py", line 22, in system_state
    return SYSTEM_STATE_NAME[value]
KeyError: 97
```

so i suspect this state is new and missing from SYSTEM_STATE_NAME dict.

Full error message:
```
2022-04-13 20:48:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/senec/__init__.py", line 116, in state
    value = getattr(self.coordinator.senec, sensor)
  File "/usr/local/lib/python3.9/site-packages/pysenec/__init__.py", line 22, in system_state
    return SYSTEM_STATE_NAME[value]
KeyError: 97
```

I can deliver more logs or infos if needed when you tell me where to find them.

**Comment by mchwalisz** [comment]
Thanks for reporting the bug and suggesting the solution.
